### ISSUE TITLE
Unapređenje beleški - Korisni online resursi (KWT)

### ISSUE THREAD

**Issue by dr460r** [Produktivna-grupa/PMFKG#5]
Ovaj Issue je namenjen za diskusiju, predloge, primedbe, u vezi unapređivanja [fajla sa linkovima do online resursa](https://github.com/studnetwork/PMFKG/blob/master/II%20godina/Letnji%20semestar/KWT/Bele%C5%A1ke/korisni-online-resursi.md) koji mogu biti korisni na predmetu Klijentske Web Tehnologije.

**Comment by TodorovicSrdjan** [comment]
@dr460r neke od ovih aktivnosti mogu da se realizuju preko [diskusija](https://github.com/studnetwork/PMFKG/discussions). Nisam nesto detaljno istrazio to, ali deluje mi da je mozda fleksibilnije od issue-a.

**Comment by dr460r** [comment]
@TodorovicSrdjan razmisljao sam o tome, ali nisam bio siguran pa na kraju rekoh da isprobam sa issue. Verovatno jeste bolje, npr. issue se otvara sa ciljem da se u jednom trenutku zatvori xD, a ovo potencijalno treba da ostane nezatvoreno. Mada diskusije dodju kao izdvojeni issue sa specificnom namenom.

**Comment by TodorovicSrdjan** [comment]
@dr460r zatvaram issue. Ukoliko neko bude želeo da nešto predloži ili napomene kasnije može da reopen-uje.
